// export const BASE_URL = process.env.VITE_API_URL || "http://localhost:7777";
export const BASE_URL = "https://spark-matcher-backend.onrender.com";

export const THEMES = [
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    // "emerald",
    "corporate",
    "synthwave",
    "retro",
    // "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
    "dim",
    "nord",
    "sunset",
  ];
